org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true

POM_GROUP=io.github.muzafferus
VERSION_NAME=0.1.0-SNAPSHOT

POM_URL=https://github.com/Muzafferus/apimirage
POM_SCM_URL=https://github.com/Muzafferus/apimirage
POM_SCM_CONNECTION=scm:git:git://github.com/Muzafferus/apimirage.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/Muzafferus/apimirage.git

POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt

POM_DEVELOPER_ID=Muzafferus
POM_DEVELOPER_NAME=Muzafferus
POM_DEVELOPER_URL=https://github.com/Muzafferus
